### PR TITLE
Fix custom hostname test.

### PR DESCRIPTION
**Pull request by zmarano**

### CODE REVIEW

**Comment by dorileo** [comment]
are we considering old use cases or are we testing it all based on the transient behavior?

**Comment by zmarano** [comment]
I'm looking at that question now for some of the older distros (EL7 and SLES 12 in particular).

**Comment by zmarano** [comment]
Custom host names do work correctly on almost all distros (except SLES). The CLI tools used to get the FQDN have changed a lot and some tools give you static hostnames, some transient hostnames, some the kernel's hostname. For what we support today `hostname -f` will get us a result for this test case but we do need to revisit hostnames and how we handle them in the future.

**Pull request merged**
