### PR TITLE
feat: Update Ubuntu releases

### PR DESCRIPTION
**Pull request by kajiya3141**
Removed 2 EOL-ed Ubuntu releases (21.04 Hirsute Hippo && 21.10 Impish Indri) and added 2 new releases (22.04 Jammy Jellyfish LTS && 22.10 Kinetic Kudu). I'll come back and add Lunar Lobster 23.04 in April :)

### CODE REVIEW

**Review by zmarano — APPROVED** [review]

**Comment by zmarano** [comment]
@kajiya3141 I think you just need to run gofmt

**Comment by kajiya3141** [comment]
> @kajiya3141 I think you just need to run gofmt

Yep you were right - was just a silly error on my end :smile: 
I've corrected it and squashed the commits, hope that's alright?

**Pull request merged**
